version: '3.9'

services:

  # Node.js App
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Tempus-Backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge